name: rrmsw-mef
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas>=1.3.0
  - numpy>=1.20.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - joblib>=1.0.0
  - pip
  - pip:
    - statsmodels>=0.13.0
    - arch>=4.18.0
    - patsy>=0.5.2
